### ISSUE TITLE
Nav Bar needed

### ISSUE THREAD

**Issue by Subhradeep10** [Coders-Community/Coders-Community#1]
![image](https://user-images.githubusercontent.com/70656957/133208573-61bfe3a9-bcaa-44c9-8656-a1ca853449ea.png)

**Comment by AsfandToor** [comment]
Assign this issue to me, I'll help.

**Comment by Subhradeep10** [comment]
@AsfandToor Sure Go Ahead

**Comment by Subhradeep10** [comment]
@AsfandToor Check , I have send you the invitation
