### ISSUE TITLE
UX/UI Design

### ISSUE THREAD

**Issue by ahamedbasha-n** [Coders-Community/Coders-Community#14]
A precise UX/UI Design for reference can help us create a better website with amazing features.
Design Tools - Figma, Sketch, Adobe XD.

**Comment by Subhradeep10** [comment]
@ahamedbasha-n So can you design other pages?

**Comment by ahamedbasha-n** [comment]
Yes Ofcourse we can do that. We can have a discussion if you are available in Discord. 
Connect with me in Discord - ahamed#9594

**Comment by Subhradeep10** [comment]
@ahamedbasha-n Sure , Go for it. I have sent the friend request
