### ISSUE TITLE
Image on the home page is not visible

### ISSUE THREAD

**Issue by ghost** [Coders-Community/Coders-Community#15]
![Screenshot 2021-09-16 08 20 53](https://user-images.githubusercontent.com/73730318/133541603-d3024655-58e0-430f-a26d-c12d5449165f.png)

**Comment by Subhradeep10** [comment]
@Pseudo-Pythonic Wanna work on these issue?

**Comment by ghost** [comment]
Sure!

**Comment by Subhradeep10** [comment]
@Pseudo-Pythonic Go ahead
