### ISSUE TITLE
DOCS : ADD CONTRIBUTIONS GUIDELINES 

### ISSUE THREAD

**Issue by rohan-kulkarni-25** [Coders-Community/Coders-Community#18]
- You can create contributions guidelines which will help first contributors 

Request to maintainers : Please Add Good First Issue label

**Comment by Subhradeep10** [comment]
@rohan-kulkarni-25 wanna work on these?

**Comment by anjali-kundliya** [comment]
I want to work over it, but could you please tell what to write in that doc??

**Comment by Subhradeep10** [comment]
@anjali-kundliya05 Write how to contruibute, How to start and all those basic steps that a beginner need

**Comment by anjali-kundliya05** [comment]
Till what time do I need to submit?
