### ISSUE TITLE
Home Page Design

### ISSUE THREAD

**Issue by Subhradeep10** [Coders-Community/Coders-Community#2]
Home Page Design is Ready, If anyone want go with it
![Coders-Community](https://user-images.githubusercontent.com/70656957/133214801-702de419-0b7f-4ef6-a4f8-0a91ea3bc214.png)

**Comment by ghost** [comment]
Hey, I am interested in contributing to your project, it will be my first open-source contribution. I would love to design and develop the home page for you. I will try my best...

**Comment by Subhradeep10** [comment]
@Subhradeep10 Sure Go for it, I am sending you the invitation mail.🚀🚀
