### ISSUE TITLE
Logo is not Visible 

### ISSUE THREAD

**Issue by Yash-Sakre** [Coders-Community/Coders-Community#21]
The logo on the Home page is not visible 

![Coder-s-Community (1)](https://user-images.githubusercontent.com/72202404/134022410-e62083d0-ca5d-4ef1-9682-49e8204dd650.png)

can I fix this?

**Comment by pragyaSingh13** [comment]
Hey! I'm interested in contributing to your project. I wanna give this issue a try, can I go for it?

**Comment by ghost** [comment]
> Hey! I'm interested in contributing to your project. I wanna give this issue a try, can I go for it?

Yes, please give it a try. You can refer to #20 for more help. 
Don't exactly know what's the problem as the logo shows up fine on my local pc.

![coder's community](https://user-images.githubusercontent.com/89587930/134185107-2d0fbc19-e4de-4344-87da-9bd8020a324f.png)

**Comment by Subhradeep10** [comment]
@pragyaSingh13 Go ahead
