### ISSUE TITLE
Zoom Issues in Browser

### ISSUE THREAD

**Issue by ritvikos** [Coders-Community/Coders-Community#24]
1. When Browser's zoom is 90%
The page looks like this,
![now 90 zoom size](https://user-images.githubusercontent.com/73193822/134076331-b1ad7910-3c90-4dc5-9156-816dc9291d4b.png)

2. When Browser's zoom is above 100%.
The page looks fine.
.

SOLUTION:
.
.
If we reduce the image's top margin and reduce width slightly, this issue will be fixed and it will render in the browser correctly.
Zoom = 90%
![90 zoom size](https://user-images.githubusercontent.com/73193822/134076686-6b25646d-b5b9-4aa1-9fd8-3c9fa57190c4.png)

OR if we increase the index, it will be fixed, but it will have accessibility issues (contrast).
Zoom = 90%
![z index](https://user-images.githubusercontent.com/73193822/134077276-c52f0976-d040-43b3-8f5f-9fbbefcbd23f.png)

BTW, I am using Chrome Version 95.0.4638.10 (Official Build) dev (64-bit) and facing rendering issues in this browser.
SHALL I FIX IT?
:D

**Comment by Subhradeep10** [comment]
It's fixed now
