### ISSUE TITLE
Unstable Page's Body

### ISSUE THREAD

**Issue by ritvikos** [Coders-Community/Coders-Community#27]
1. At 90% size in browser, the page looks
![size 90](https://user-images.githubusercontent.com/73193822/134709106-052378b1-1fe0-4415-a287-e0ca7958c512.png)

2. At 100% size in browser, page looks:
![size 100](https://user-images.githubusercontent.com/73193822/134709194-b80d9c29-fb1c-4e25-b628-ab6c122203fb.png)

3. Above 100% it looks fine:
![size above 100](https://user-images.githubusercontent.com/73193822/134709290-252466bf-f304-4527-becd-82c89951ef87.png)

**Comment by Subhradeep10** [comment]
@Ritvik-UX It is fixed now..Check it
