### ISSUE TITLE
Logo Not Visible on Site's Link in About Section in Github

### ISSUE THREAD

**Issue by ritvikos** [Coders-Community/Coders-Community#29]
Logo Not Visible at https://coders-community.github.io/Coders-Community/
isn't this page updated or it's a bug?

**Comment by Subhradeep10** [comment]
@Ritvik-UX THat's a bug...wanna work for the issue?

**Comment by coder2800** [comment]
@Subhradeep10 can you please add hacktoberfest labels to these issues and can you assign this to me ?

**Comment by Subhradeep10** [comment]
@coder284 Actually I haven't registered my repo for Hacktoberfest..Don't worry ..It is registered in other Open Source
