### ISSUE TITLE
About Us

### ISSUE THREAD

**Issue by Subhradeep10** [Coders-Community/Coders-Community#3]
About Us Design is ready, It will be below the Home Section
![Coders-Community](https://user-images.githubusercontent.com/70656957/133215561-73141469-0390-4e5b-b4a0-5129eb69df54.png)

**Comment by coder2800** [comment]
@Subhradeep10 can you please upload this image? Or is it fine if i use any image?

**Comment by Subhradeep10** [comment]
Join the discord link https://discord.gg/FZ8EBRDa

I will give the images there

**Comment by coder2800** [comment]
Oh sorry, I saw this message after i had created the pull request. For now i have added another image.

**Comment by Subhradeep10** [comment]
@coder284 I had reviwed the code.
