### ISSUE TITLE
Project's Page

### ISSUE THREAD

**Issue by Subhradeep10** [Coders-Community/Coders-Community#5]
Project's Page Design is Ready
![Coders-Community (1)](https://user-images.githubusercontent.com/70656957/133272267-1b3dd71f-9070-4cc0-9ab7-7e061ff48bf6.png)

**Comment by lostgirljourney** [comment]
I can help. 👋🏼

**Comment by Subhradeep10** [comment]
@lostgirljourney Yeah sure, Go ahead
