### ISSUE TITLE
Footer Page

### ISSUE THREAD

**Issue by Subhradeep10** [Coders-Community/Coders-Community#6]
Footer Page design is ready
![image](https://user-images.githubusercontent.com/70656957/133272719-c81170f6-2ded-4115-9430-2f114dc91070.png)

**Comment by goverdhan07** [comment]
Hi, can you assign me! want to fix this issue :)

**Comment by Subhradeep10** [comment]
@goverdhan07 Already done by someone else. 
Dont worry, there 's  other's issue posted. You can look into that
